#
# Project:	Network Information Transfer System (NITS)
# Module:	
# Programmer:	John C. Noble
# Organization:	JHU EP
# Host System:	SunOS 4
# Date Created: February 10
# Modifications:
#	$Log$
# 
# 

# Library to make (eg: libeg.a)
LIBRARY = arg.a 


# Source files for LIBRARY routines
SRC	= getarg.c

# Master include files for libraries.
include ../../../Make_templates/Make.lib
